name: 'Staging test/build/deploy'
description: 'Run unit tests, build binaries and upload to staging location'
author: 'Anton Pyrogovskyi <anton@wireleap.com>'
inputs:
  token:
    description: 'Token to access private repos and dispatch assembly workflow'
    required: true
  ssh_key:
    description: 'SSH private key for artifact upload to staging location'
    required: true
  upload_target:
    description: 'Where to upload artifacts to (ssh/scp-style path: user@host:dir/)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Fix https://github.com/actions/checkout/issues/290
      run: "cd ${{ github.workspace }} && git fetch --tags --force"
      shell: sh
    - name: Set up private repo access
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: "cat ${{ github.action_path }}/gitconfig-template | envsubst > ${{ github.action_path }}/gitconfig"
      shell: sh
    - name: Get dependencies, build and run unit tests
      env:
        DOCKER_OPTS: "-v ${{ github.action_path }}/gitconfig:/root/.gitconfig"
      run: "${{ github.workspace }}/contrib/docker/run-tests.sh"
      shell: sh
    - name: Build binaries
      env:
        DOCKER_OPTS: "-v ${{ github.action_path }}/gitconfig:/root/.gitconfig"
      run: "${{ github.workspace }}/contrib/docker/build-bin.sh build"
      shell: sh
    - name: Clean up private repo gitconfig
      run: "shred -u ${{ github.action_path }}/gitconfig"
      shell: sh
    - name: Set up SSH
      run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ inputs.ssh_key }}" > "$HOME/.ssh/id_rsa"
          chmod go-rwx "$HOME/.ssh/id_rsa"
          cp ${{ github.action_path }}/known_hosts "$HOME/.ssh/known_hosts"
      shell: sh
    - name: Deploy to staging location
      run: "rsync -e 'ssh -o RequestTTY=no' -WavK build/ ${{ inputs.upload_target }}"
      shell: sh
    - name: Trigger assembly workflow
      run: "echo TODO"
      shell: sh
