name: 'Staging test/build/deploy'
description: 'Run unit tests, build binaries and upload to staging location'
author: 'Anton Pyrogovskyi <anton@wireleap.com>'
inputs:
  ssh_key:
    description: 'SSH private key for private repo access & upload'
    required: true
  upload_target:
    description: 'Where to upload artifacts to (ssh/scp-style path: user@host:dir/)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get dependencies, build and run unit tests
      run: "${{ github.workspace }}/contrib/docker/run-tests.sh"
    - name: Build binaries
      run: "${{ github.workspace }}/contrib/docker/build-bin.sh build"
    - name: Set up SSH
      run: "${{ github.action_path }}/helpers/setup-ssh.sh" "${{ inputs.ssh_key }}"
    - name: Deploy to staging location
      run: "rsync -e 'ssh -o RequestTTY=no' -WavK build/ ${{ inputs.upload_target }}"
